name: Setup Node.js environment
on: [push]
jobs: 
  install-nodejs:
    runs-on: ubuntu-lastest
    uses: actions/setup-node@v2.3.0
    steps:
      uses: actions/checkout@v2
      uses: actions/setup-node@v2
      with:
        node-version: '14'
      run: npm install
      run: npm test